# 스프링 부트 설정 파일

# 현재 Spring Boot 애플리케이션 이름 설정
spring.application.name=board

# H2 Database 콘솔 사용 설정
# 브라우저에서 DB 확인 가능하게 해준다.
spring.h2.console.enabled=true

# H2 Database 연결 주소
# 현재는 메모리 DB 사용
spring.datasource.url=jdbc:h2:mem:testdb

# H2 Database 드라이버
spring.datasource.driverClassName=org.h2.Driver

# DB 사용자 이름
spring.datasource.username=sa

# 비밀번호
# H2 기본 설정은 비워둔다.
spring.datasource.password=

# 서버 실행 시 Entity 보고 테이블 자동 생성
spring.jpa.hibernate.ddl-auto=create

# 실행되는 SQL을 콘솔에 출력
spring.jpa.show-sql=true